// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Address struct {
	HouseNo  string `json:"houseNo"`
	Street   string `json:"street"`
	City     string `json:"city"`
	District string `json:"district"`
	State    string `json:"state"`
	Country  string `json:"country"`
	PinCode  string `json:"pinCode"`
}

type AuthUser struct {
	Email       string `json:"email"`
	DisplayName string `json:"displayName"`
	Token       string `json:"token"`
	Expiry      int    `json:"expiry"`
}

type BasicUser struct {
	ID          string  `json:"id"`
	DisplayName string  `json:"displayName"`
	Rating      float64 `json:"rating"`
}

type ChangePassword struct {
	OldPassword     string `json:"oldPassword"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type Chat struct {
	ID         string     `json:"id"`
	UserID     string     `json:"userId"`
	ReceiverID string     `json:"receiverId"`
	Messages   []*Message `json:"messages"`
}

type Credential struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Enquiry struct {
	ID         string `json:"id"`
	PostID     string `json:"postId"`
	UserID     string `json:"userId"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	Subject    string `json:"subject"`
	Content    string `json:"content"`
	MessagedAt int    `json:"messagedAt"`
	IsRead     bool   `json:"isRead"`
}

type History struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

type Image struct {
	Title       string `json:"title"`
	URL         string `json:"url"`
	ThumbURL    string `json:"thumbUrl"`
	Description string `json:"description"`
}

type Message struct {
	Content    *string       `json:"content"`
	Image      *MessageImage `json:"image"`
	IsRead     bool          `json:"isRead"`
	MessagedAt int           `json:"messagedAt"`
}

type MessageImage struct {
	URL      *string `json:"url"`
	ThumbURL *string `json:"thumbUrl"`
}

type NewEnquiry struct {
	PostID  string `json:"postId"`
	Name    string `json:"name"`
	Email   string `json:"email"`
	Phone   string `json:"phone"`
	Subject string `json:"subject"`
	Content string `json:"content"`
}

type NewMessage struct {
	ReceiverID *string         `json:"receiverId"`
	Content    *string         `json:"content"`
	Image      *graphql.Upload `json:"image"`
}

type NewPost struct {
	Title          string       `json:"title"`
	Description    string       `json:"description"`
	Images         []*PostImage `json:"images"`
	Price          float64      `json:"price"`
	Tags           []*string    `json:"tags"`
	Platforms      []*string    `json:"platforms"`
	Language       string       `json:"language"`
	ExpectedViews  int          `json:"expectedViews"`
	Duration       int          `json:"duration"`
	AvailableFrom  int          `json:"availableFrom"`
	PublishingDate int          `json:"publishingDate"`
	CreatedAt      int          `json:"createdAt"`
	Country        *string      `json:"country"`
	State          *string      `json:"state"`
	City           *string      `json:"city"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type Paging struct {
	Offset int `json:"offset"`
	Limit  int `json:"limit"`
}

type Portfolio struct {
	Title    string   `json:"title"`
	Platform string   `json:"platform"`
	URL      string   `json:"url"`
	Images   []*Image `json:"images"`
}

type Post struct {
	ID             string     `json:"id"`
	UserID         string     `json:"userId"`
	Title          string     `json:"title"`
	URL            string     `json:"url"`
	Description    string     `json:"description"`
	Images         []*Image   `json:"images"`
	Price          *float64   `json:"price"`
	Tags           []*string  `json:"tags"`
	Platform       string     `json:"platform"`
	Language       string     `json:"language"`
	ExpectedViews  string     `json:"expectedViews"`
	Duration       int        `json:"duration"`
	Sponsors       *string    `json:"sponsors"`
	Status         string     `json:"status"`
	IsActive       bool       `json:"isActive"`
	AvailableFrom  int        `json:"availableFrom"`
	PublishingDate int        `json:"publishingDate"`
	CreatedAt      int        `json:"createdAt"`
	City           string     `json:"city"`
	State          string     `json:"state"`
	Country        string     `json:"country"`
	User           *BasicUser `json:"user"`
}

type PostFilter struct {
	Paging *Paging     `json:"paging"`
	Filter *PostFilter `json:"filter"`
	Order  *SortOrder  `json:"order"`
}

type PostImage struct {
	Title       string `json:"title"`
	Image       string `json:"image"`
	Description string `json:"description"`
}

type SearchFilter struct {
	Keyword  string    `json:"keyword"`
	SearchOn string    `json:"searchOn"`
	Tags     []*string `json:"tags"`
	UserID   string    `json:"userId"`
}

type SortOrder struct {
	SortBy string `json:"sortBy"`
	Order  bool   `json:"order"`
}

type User struct {
	ID                 string     `json:"id"`
	FirstName          string     `json:"firstName"`
	LastName           string     `json:"lastName"`
	DisplayName        string     `json:"displayName"`
	URL                string     `json:"url"`
	ProfileImage       *Image     `json:"profileImage"`
	ProfileImageURL    string     `json:"profileImageUrl"`
	Description        string     `json:"description"`
	Address            *Address   `json:"address"`
	Phone              string     `json:"phone"`
	Email              string     `json:"email"`
	Username           string     `json:"username"`
	Password           string     `json:"password"`
	VerificationKey    string     `json:"verificationKey"`
	VerificationExpiry int        `json:"verificationExpiry"`
	RegisteredOn       int        `json:"registeredOn"`
	IsCompany          bool       `json:"isCompany"`
	Rating             int        `json:"rating"`
	Frequency          string     `json:"frequency"`
	AvgViews           int        `json:"avgViews"`
	Customers          string     `json:"customers"`
	Level              int        `json:"level"`
	Posts              []*Post    `json:"posts"`
	History            []*History `json:"history"`
}
